image: docker:latest
services:
  - docker:dind

variables:
  BUILD_DIR: "."
  VERSION: "dev-1.0.1"
  IMAGE_NAME: "globalmpire/fb-research"

before_script:
  - whoami && pwd && date


build:
  stage: build
  only:
    - development
  script:
    - apk add --no-cache curl jq python3 py3-pip zip
    - pip install awscli
    - docker build . -t $IMAGE_NAME:$VERSION
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - docker push $IMAGE_NAME:$VERSION
    - sh deploy.sh
  tags:
    - docker
  when: manual


